### ISSUE TITLE
功能 Coding Plan

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#148]
所有新的代码请大家 PR 到 v1 分支。

- [x] 单基因分析功能的完善（<https://github.com/openbiox/UCSCXenaShiny/issues/140>，<https://github.com/openbiox/UCSCXenaShiny/issues/144>，<https://github.com/openbiox/UCSCXenaShiny/issues/72>）（主题统一为 theme_cowplot 或 theme_base）- 负责人：熊逸
- [x] 生存分析功能的完善（<https://github.com/openbiox/UCSCXenaShiny/issues/91>）- 负责人：赵龙飞
- [x] Hiplot 镜像引入，加速数据下载（<https://github.com/openbiox/UCSCXenaShiny/issues/143>）- 负责人：王诗翔
- [x] CCLE 药物敏感性展示（<https://github.com/openbiox/UCSCXenaShiny/issues/119>）这是一个很不错的新增功能。- 负责人：顾凯
- [x] 包内置大数据集标注、另外存储和加载（<https://github.com/openbiox/UCSCXenaShiny/issues/147>）。- 负责人：王诗翔
- [x] 对接 Xena 任意常见数据集的分析流程打造。用户先选数据集，我们代码标定数据集 然后选择分析功能 再根据需要过滤数据 最后运行分析，目前准备支持相关与分组比较分析。负责人：王诗翔，龙飞、顾凯作为主要参与人。
- [x] Help 页面整理。（负责人：所有人）
- [x] 包公开数据获取与可视化接口整理。（负责人：王诗翔与熊逸）
- [x] Shiny 整个页面优化。（负责人：王诗翔）
- [x] 全部的绘图结果都尽量支持相应表格数据下载，这是一个值得支持的亮点特性。

zenodo 数据集地址：<https://zenodo.org/record/4625640>，已经在包内写好了载入接口函数 `load_data()`

**Comment by ShixiangWang** [comment]
@kaigu1990 

看下数据的行列含义，然后常用的分析来一套即可

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5554885/

https://www.google.com.hk/search?q=ccle+drug+response+visualization&newwindow=1&safe=strict&sxsrf=ALeKk03gE8Tjzm3pWyzU8k-G5in1JXNrAQ:1615555319416&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi7yrbH7KrvAhWMP3AKHRpDCtwQ_AUoAXoECAIQAw

**Comment by Byronxy** [comment]
![image](https://user-images.githubusercontent.com/28949856/111020134-946c7600-83fe-11eb-8095-d43e989f51a8.png)
补充这个help页面的说明

**Comment by ShixiangWang** [comment]
参考：https://stackoverflow.com/questions/61231769/expand-collapse-shiny-selectinput-function，用于 repository 页面数据集选择优化。

**Comment by ShixiangWang** [comment]
- [ ] 全部的结果都支持相应表格数据下载，这是一个值得支持的亮点特性。
